language: cpp

os:
  - linux
  
compiler:
  - clang

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libstdc++-4.8-dev; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/versions; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install gcc49; fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-add-repository -y ppa:boost-latest/ppa; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libboost1.55-all-dev; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install boost; fi

  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then CMAKE_VERSION="3.0.0"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget "http://www.cmake.org/files/v3.0/cmake-${CMAKE_VERSION}.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then openssl sha1 "cmake-${CMAKE_VERSION}.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar xf "cmake-${CMAKE_VERSION}.tar.gz"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd "cmake-${CMAKE_VERSION}"; fi

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cmake; fi

  - ./bootstrap --prefix=~

  - make
  - make install
  - export PATH="~/bin:${PATH}"
  - cd ..
  - which cmake
  - cmake --version
  - which g++
  - g++ -v

before_script:
  - sudo apt-get install tar
  - sudo apt-get install gzip

script:
  - mkdir build
  - cd build
  - ~/bin/cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake ..; fi
  - make

notifications:
  email:
    recipients:
      - stewart.henderson@live.com
    on_success: change
    on_failure: change

deploy:
  provider: releases
  api-key: "9a7cf431250dc0747287bd21c7ea53529fe0e61e"
  file: "http-to-kafka"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
